#ifndef GUI_RESOURCE_MAP_H
#define GUI_RESOURCE_MAP_H

#include <stdint.h>

/* W25Q256: 32MB
 * 资源区: 0x00000000 - 0x00FFFFFF (16MB)
 * FatFs区: 0x01000000 - 0x01FFFFFF (16MB)
 */
#define QSPI_MMAP_BASE            0x90000000UL
#define QSPI_RESOURCE_OFFSET      0x00000000UL
#define QSPI_RESOURCE_SIZE        0x01000000UL
#define QSPI_FATFS_OFFSET         0x01000000UL
#define QSPI_FATFS_SIZE           0x01000000UL

#define QSPI_RES_SLOT_SIZE        0x00010000UL /* 64KB per resource (icons) */
#define QSPI_FONT_SLOT_SIZE       0x00200000UL /* 2MB per font */

/* 资源完整性标记区（放在资源区最后一个 4KB 扇区） */
#define RES_MAGIC_OFFSET          (QSPI_RESOURCE_OFFSET + QSPI_RESOURCE_SIZE - 0x00001000UL)
#define RES_MAGIC_VALUE           0x51535049UL /* 'QSPI' */
#define RES_MAGIC_VERSION         0x00000001UL

typedef enum {
    GUI_RES_ICON_01 = 0,
    GUI_RES_ICON_02,
    GUI_RES_ICON_03,
    GUI_RES_ICON_04,
    GUI_RES_ICON_05,
    GUI_RES_ICON_06,
    GUI_RES_ICON_07,
    GUI_RES_ICON_08,
    GUI_RES_ICON_09,
    GUI_RES_ICON_10,
    GUI_RES_ICON_11,
    GUI_RES_ICON_12,
    GUI_RES_ICON_13,
    GUI_RES_ICON_14,
    GUI_RES_FONT_12,
    GUI_RES_FONT_14,
    GUI_RES_FONT_16,
    GUI_RES_FONT_20,
    GUI_RES_FONT_30,
    GUI_RES_PINYIN_DICT,
    GUI_RES_COUNT
} gui_res_id_t;

#define RES_ICON_01_OFFSET         (QSPI_RESOURCE_OFFSET + 0x00000000UL)
#define RES_ICON_02_OFFSET         (QSPI_RESOURCE_OFFSET + 0x00010000UL)
#define RES_ICON_03_OFFSET         (QSPI_RESOURCE_OFFSET + 0x00020000UL)
#define RES_ICON_04_OFFSET         (QSPI_RESOURCE_OFFSET + 0x00030000UL)
#define RES_ICON_05_OFFSET         (QSPI_RESOURCE_OFFSET + 0x00040000UL)
#define RES_ICON_06_OFFSET         (QSPI_RESOURCE_OFFSET + 0x00050000UL)
#define RES_ICON_07_OFFSET         (QSPI_RESOURCE_OFFSET + 0x00060000UL)
#define RES_ICON_08_OFFSET         (QSPI_RESOURCE_OFFSET + 0x00070000UL)
#define RES_ICON_09_OFFSET         (QSPI_RESOURCE_OFFSET + 0x00080000UL)
#define RES_ICON_10_OFFSET         (QSPI_RESOURCE_OFFSET + 0x00090000UL)
#define RES_ICON_11_OFFSET         (QSPI_RESOURCE_OFFSET + 0x000A0000UL)
#define RES_ICON_12_OFFSET         (QSPI_RESOURCE_OFFSET + 0x000B0000UL)
#define RES_ICON_13_OFFSET         (QSPI_RESOURCE_OFFSET + 0x000C0000UL)
#define RES_ICON_14_OFFSET         (QSPI_RESOURCE_OFFSET + 0x000D0000UL)

#define RES_FONT_12_OFFSET         (QSPI_RESOURCE_OFFSET + 0x00100000UL)
#define RES_FONT_14_OFFSET         (QSPI_RESOURCE_OFFSET + 0x00300000UL)
#define RES_FONT_16_OFFSET         (QSPI_RESOURCE_OFFSET + 0x00500000UL)
#define RES_FONT_20_OFFSET         (QSPI_RESOURCE_OFFSET + 0x00700000UL)
#define RES_FONT_30_OFFSET         (QSPI_RESOURCE_OFFSET + 0x00900000UL)

#define QSPI_PINYIN_OFFSET         (QSPI_RESOURCE_OFFSET + 0x00B00000UL)
#define QSPI_PINYIN_SIZE           (RES_MAGIC_OFFSET - QSPI_PINYIN_OFFSET)
#define RES_PINYIN_DICT_OFFSET     QSPI_PINYIN_OFFSET

typedef struct {
    uint32_t offset;
    uint32_t max_size;
} gui_res_map_t;

static const gui_res_map_t g_gui_res_map[GUI_RES_COUNT] = {
    { RES_ICON_01_OFFSET, QSPI_RES_SLOT_SIZE },
    { RES_ICON_02_OFFSET, QSPI_RES_SLOT_SIZE },
    { RES_ICON_03_OFFSET, QSPI_RES_SLOT_SIZE },
    { RES_ICON_04_OFFSET, QSPI_RES_SLOT_SIZE },
    { RES_ICON_05_OFFSET, QSPI_RES_SLOT_SIZE },
    { RES_ICON_06_OFFSET, QSPI_RES_SLOT_SIZE },
    { RES_ICON_07_OFFSET, QSPI_RES_SLOT_SIZE },
    { RES_ICON_08_OFFSET, QSPI_RES_SLOT_SIZE },
    { RES_ICON_09_OFFSET, QSPI_RES_SLOT_SIZE },
    { RES_ICON_10_OFFSET, QSPI_RES_SLOT_SIZE },
    { RES_ICON_11_OFFSET, QSPI_RES_SLOT_SIZE },
    { RES_ICON_12_OFFSET, QSPI_RES_SLOT_SIZE },
    { RES_ICON_13_OFFSET, QSPI_RES_SLOT_SIZE },
    { RES_ICON_14_OFFSET, QSPI_RES_SLOT_SIZE },
    { RES_FONT_12_OFFSET, QSPI_FONT_SLOT_SIZE },
    { RES_FONT_14_OFFSET, QSPI_FONT_SLOT_SIZE },
    { RES_FONT_16_OFFSET, QSPI_FONT_SLOT_SIZE },
    { RES_FONT_20_OFFSET, QSPI_FONT_SLOT_SIZE },
    { RES_FONT_30_OFFSET, QSPI_FONT_SLOT_SIZE },
    { RES_PINYIN_DICT_OFFSET, QSPI_PINYIN_SIZE },
};

static inline uint32_t gui_res_offset(gui_res_id_t id)
{
    return g_gui_res_map[id].offset;
}

static inline uint32_t gui_res_max_size(gui_res_id_t id)
{
    return g_gui_res_map[id].max_size;
}

static inline const uint8_t * gui_res_mmap_ptr(gui_res_id_t id)
{
    return (const uint8_t *)(QSPI_MMAP_BASE + gui_res_offset(id));
}

#endif /* GUI_RESOURCE_MAP_H */
