#pragma once

#define APP_DEFAULT_WIFI_SSID "YOUR_WIFI_SSID"
#define APP_DEFAULT_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define APP_DEFAULT_SERVER_HOST "YOUR_SERVER_HOST_OR_IP"
#define APP_DEFAULT_SERVER_PORT 8080U
#define APP_DEFAULT_NODE_ID "STM32_RTOS_Device"
#define APP_DEFAULT_NODE_LOCATION "EdgeWind Lab"
#define APP_DEFAULT_HW_VERSION "ESP32-SPI-Coprocessor"
